### PR TITLE
Feature/php 8.0 rc with pickle

### PR DESCRIPTION
**Pull request by renatomefi**
# Usabilla PHP Docker Template

Reviewers: @usabilla/oss-docker

## Type

Please specify the type of changes being proposed:

| Q                 | A
| ----------------- | -----
| Documentation?    | yes/no
| Dockerfile change?| yes/no
| Build feature?    | yes/no
| Apply CVE Patch?  | yes/no
| Remove CVE Patch? | yes/no

## Changelog

- Please make sure you have checked our [Contributing guidelines](https://github.com/usabilla/php-docker-template/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by carusogabriel** [comment]
@WyriHaximus We need:

- XDebug 3 (the xdebug version that is compatible with PHP 8.0)
- `arnaud-lb/php-rdkafka` needs to be updated to support PHP 8.0. See https://github.com/usabilla/php-docker-template/pull/156#issuecomment-655518548

**Comment by renatomefi** [comment]
I'm not finishing this PR, please you 2 can take it over :D

**Comment by bendavies** [comment]
any interest in getting this over the line? :)

**Comment by agustingomes** [comment]
@bendavies we're still studying some options, this week we were able to build base images with PEAR for php8. but before we continue with the adoption of php8, we'll need to adopt Xdebug 3, because Xdebug 2 is not compatible with PHP8.

**Comment by carusogabriel** [comment]
Closing in favour of #179.

**Pull request closed without merging**
