### PR TITLE
Start building PHP 8.0 images

### PR DESCRIPTION
**Pull request by carusogabriel**
Reviewers: @usabilla/oss-docker

### CODE REVIEW

**Review by WyriHaximus — APPROVED** [review]
:tada: Let's get PHP 8.0 out there :tada:

**Review by WyriHaximus — APPROVED** [review]

**Review by cvmiert — COMMENTED** [review]
@carusogabriel I noticed you're using the [Alpine Linux release page](https://alpinelinux.org/releases/) to determine which versions are still supported.

I'd like to point out that we're using the Alpine-based [official PHP Docker images](https://hub.docker.com/_/php) as our base image, not the Alpine Linux distribution itself (you can run it as an OS, like any other Linux flavour).

I think we should be looking [here](https://github.com/docker-library/docs/blob/master/php/README.md#supported-tags-and-respective-dockerfile-links) instead for information about active support.

**Comment by bendavies** [comment]
💯💥 excellent!

**Comment by carusogabriel** [comment]
We will wait for #176, so we can test those changes with PHP 8.0 images as well.

**Review by cvmiert — APPROVED** [review]

**Comment by bendavies** [comment]
forgot to update  https://github.com/usabilla/php-docker-template/blob/master/Makefile#L18-L43?

**Comment by carusogabriel** [comment]
@bendavies We might be able to remove it, actually. 

Since #160, we have been building our images with GitHub Actions: https://github.com/usabilla/php-docker-template/blob/c6228a18696d/.github/workflows/ci.yml#L149-L189

**Comment by carusogabriel** [comment]
Habemus PHP 8.0 Docker images: https://hub.docker.com/r/usabillabv/php/tags?page=1&ordering=last_updated&name=8.0

**Comment by WyriHaximus** [comment]
@carusogabriel @bendavies IMHO both are preferably using the same source to feed that in the future. That make command is still very useful to check locally if everything builds fine. (Giving it takes half an hour locally compared to a few minutes on GA :zipper_mouth_face: .)

**Pull request merged**
