### PR TITLE
Build PHP 8.0-rc

### PR DESCRIPTION
**Pull request by carusogabriel**
## Type

Please specify the type of changes being proposed:

| Q                 | A
| ----------------- | -----
| Documentation?    | no
| Dockerfile change?| no
| Build feature?    | yes
| Apply CVE Patch?  | no
| Remove CVE Patch? | no

## Changes

TBD.

### CODE REVIEW

**Comment by carusogabriel** [comment]
Looks like this is going to need some extra work: https://github.com/docker-library/php/issues/846 😕

**Comment by renatomefi** [comment]
@carusogabriel for your pleasure: https://github.com/usabilla/php-docker-template/pull/158

Options:
- Use pickle
- Add `with-pear` to our images
- Convince upstream to add `with-pear`
- Use a build target to use pecl
- More options?

**Comment by carusogabriel** [comment]
To align: https://github.com/arnaud-lb/php-rdkafka/issues/328.

Once we have that, we can move with PHP 8, and with Renato's approach on #158 using https://github.com/FriendsOfPHP/pickle.

**Comment by nick-zh** [comment]
FYI: php-rdkafka:5.0 was just released

**Comment by carusogabriel** [comment]
Closing in favour of #179.

**Pull request closed without merging**
