### PR TITLE
Build PHP 8.1 images

### PR DESCRIPTION
**Pull request by WyriHaximus**
# Usabilla PHP Docker Template

Reviewers: @usabilla/oss-docker

## Type

Please specify the type of changes being proposed:

| Q                 | A
| ----------------- | -----
| Documentation?    | no
| Dockerfile change?| no
| Build feature?    | yes
| Apply CVE Patch?  | no
| Remove CVE Patch? | no

### CODE REVIEW

**Comment by WyriHaximus** [comment]
> This _should_ not work: the GPG keys for the PHP 8.1 RMs is missing :)
> 
> You can download them at https://php.net/gpg-keys

On that now, we also should really fix the build matrix :zipper_mouth_face:

**Comment by WyriHaximus** [comment]
FYI I will make a bunch of commits and pushes in a row to figure out why certain parts of the build might fail. The first one is due to libsodium on 8.1

**Review by carusogabriel — APPROVED** [review]
Would you mind rebasing this one on top of #182? Otherwise, thanks for this addition!

**Comment by WyriHaximus** [comment]
> Would you mind rebasing this one on top of #182?

That was the plan all along 😈

**Pull request merged**
