### PR TITLE
Enable Buildkit

### PR DESCRIPTION
**Pull request by bendavies**
# Usabilla PHP Docker Template

Reviewers: @usabilla/oss-docker

## Type

Please specify the type of changes being proposed:

| Q                 | A
| ----------------- | -----
| Documentation?    | no
| Dockerfile change?| no
| Build feature?    | yes
| Apply CVE Patch?  | no
| Remove CVE Patch? | no

## Changelog

- Use Buildkit when building images

### CODE REVIEW

**Comment by renatomefi** [comment]
Hello @bendavies, very nice, thanks for that!

Seems like the build is alright but the docker inspect command might have changed with buildkit, maybe the trick to run the `docker inspect` command and see the path of the information we'd like to use!

**Comment by renatomefi** [comment]
You can also do that locally to save you some time!

**Comment by bendavies** [comment]
I don't know why, but `ContainerConfig.Env` in `docker inspect` is blank with buildkit enabled.

**Comment by bendavies** [comment]
`Config.Env` has the correct info still, but unsure of the difference between `ContainerConfig` and `Config`. both are populated without buildkit.

**Comment by bendavies** [comment]
@renatomefi I can switch the inspect commands to use `Config.Env`, but i'm unsure of the implications. this is all i've found really: https://stackoverflow.com/a/36216632

**Comment by renatomefi** [comment]
Hey @bendavies , I think replacing it is fine, let's give that a try!

Thanks

**Comment by bendavies** [comment]
so close

**Comment by bendavies** [comment]
@renatomefi try rebuilding?

**Comment by renatomefi** [comment]
No luck here either :(

**Comment by bendavies** [comment]
@renatomefi do you understand the test failure output?

**Comment by bendavies** [comment]
seems the filemode is 755 instead of 775

**Comment by bendavies** [comment]
i don't understand why the test tests for 775.
the perms are 755 in the git repo.
```
stat -f %A src/php/utils/docker/docker-php-dev-mode
755
```

**Comment by bendavies** [comment]
i can update the test to match if that is agreed appropriate.

**Comment by renatomefi** [comment]
Hey @bendavies, awesome to see that's the only issue now, what was the fix of the previous problem?
Go ahead and update the test, it might be a collateral damange of how docker without buildkit works, in this case we only want to guarantee the file is executable!

**Comment by bendavies** [comment]
fixed pushed.
I think these were the same failures as before, I just didn't look into it!

**Comment by bendavies** [comment]
The fun continues, some files are 775, some are 755

**Comment by bendavies** [comment]
ok, so all the scripts in the official php image are 775:
`docker run --rm -it php:7.4-cli-alpine3.11 ls -hal /usr/local/bin/`

all of ours are 755. tests updated accordingly.

**Comment by bendavies** [comment]
@renatomefi we're good

**Pull request merged**
